# PySceneDetect Website (https://www.scenedetect.com)
# Copyright (C) 2014-2023 Brandon Castellano <http://www.bcastell.com>.
site_name: PySceneDetect
site_description: "Website and documentation for PySceneDetect, a program to automatically detect scene cuts and split videos.  Written in Python, and also provides Python API in addition to command-line interface for use within other programs."
site_author: "Brandon Castellano"
docs_dir: "pages"
site_dir: "build"
repo_url: https://github.com/Breakthrough/PySceneDetect
repo_name: "PySceneDetect on Github"
copyright: 'Copyright &copy; 2014-2023 Brandon Castellano.  All rights reserved.<br />Licensed under BSD 3-Clause (see the <a href="https://github.com/Breakthrough/PySceneDetect/blob/main/LICENSE" alt="link to latest LICENSE file on Github">LICENSE file</a> for details).'
theme: readthedocs
# TODO: deprecated option for this theme
google_analytics: ['UA-72551323-1', 'auto']

# TODO: `pages` is deprecated, use `nav` instead
pages:
- 'PySceneDetect':
    - 'Home': 'index.md'
    - 'Features': 'features.md'
    - 'Download': 'download.md'
    - 'Changelog': 'changelog.md'
- 'Reference:':
    - 'Documentation': 'docs.md'
    - 'Command-Line': 'cli.md'
    - 'Python API': 'api.md'
- 'Support:':
    - 'FAQ': 'faq.md'
    - 'Bugs & Contributing': 'contributing.md'
    - 'Development & Support': 'supporting.md'
- 'Resources':
    - 'Similar Projects': 'similar.md'
    - 'Research & Literature': 'literature.md'
    - 'License & Copyright': 'copyright.md'

markdown_extensions: [fenced_code]
