# Use YAPF to format PySceneDetect.
name: Check Code Format

on:
  pull_request:
    paths:
      - scenedetect/**
      - tests/**
  push:
    paths:
      - scenedetect/**
      - tests/**

jobs:
  check_format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install yapf
        run: python -m pip install --upgrade yapf toml

      - name: Install Binary Dependencies
        run: python -m pip install av opencv-python-headless --only-binary ":all:"
      - name: Install Remaining Dependencies
        run: python -m pip install -r requirements_headless.txt

      - name: Check Code Format (scenedetect)
        run: python -m yapf --diff --recursive scenedetect/
      - name: Check Code Format (tests)
        run: python -m yapf --diff --recursive tests/
